---
platform: linux 

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: sourceCode

outputs:
  - name: jarFile
  
run:
 path: sh
 args: ["ci/build.sh"]
