---
# Docker image resource type for email notification
resource_types:
- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource

# Pipeline resources
resources:
# Git clone resource
- name: sourceCode
  type: git
  source:
    uri: https://github.com/pp010/helloworld.git
    branch: master
    username: {{git-username}}
    password: {{git-password}} 
# CF deployment resource
- name: AppDeploy
  type: cf
  source:
    api: https://api.system.dev.digifabricpcf.com
    username: {{cf-username}}
    password: {{cf-password}}
    organization: SkyLight
    space: Development
    skip_cert_check: true
# Email notification resource
- name: notification
  type: email
  source:
    smtp:
      host: smtp.gmail.com
      port: "587"
      username: {{smtp-username}}
      password: {{smtp-password}}
    from: wydnpipeline@gmail.com
    to: ["padarabinda.panigrahi@cognizant.com"]
# Time trigger resource
- name: scheduleBuild
  type: time
  source:
    interval: 5h
    start: 12:30 PM
    stop: 06:30 PM
    location: Asia/Kolkata

jobs:
- name: buildAndDeploy
  # Avoid parallel jobs
  serial: true
  plan: 
  - get: scheduleBuild
    trigger: true
    # Git clone
  - get: sourceCode
  - task: build
    privileged: true
    file: sourceCode/ci/build.yml
    # Trigger email notification on build status
    on_success:
      do:
      - task: email-content
        file: sourceCode/ci/git-client-build-success.yml
      - put: notification
        params:
          subject: email-content/subject.txt
          body: email-content/body.txt
    on_failure:
      do:
      - task: email-content
        file: sourceCode/ci/git-client-build-fail.yml
      - put: notification
        params:
          subject: email-content/subject.txt
          body: email-content/body.txt
    # CF push
  - put: AppDeploy
    params:
      manifest: sourceCode/manifest.yml
      path: jarFile/*.jar
    # Trigger email notification on deploy status
    on_success:
      do:
      - task: email-content
        file: sourceCode/ci/git-client-deploy-success.yml
      - put: notification
        params:
          subject: email-content/subject.txt
          body: email-content/body.txt
    on_failure:
      do:
      - task: email-content
        file: sourceCode/ci/git-client-deploy-fail.yml
      - put: notification
        params:
          subject: email-content/subject.txt
          body: email-content/body.txt